production:
  clients:
    default:
      database: fret_heatmap_app_production
      uri: <%= ENV['MONGODB_URI'] %>

development:
  clients:
    default:
      database: fret_heatmap_app_development
      hosts:
        - localhost:27017
      options:
        # The name of the user for authentication.
        # user: 'user'

        # The password of the user for authentication.
        # password: 'password'

        # The user's database roles.
        # roles:
        #   - 'dbOwner'
test:
  clients:
    default:
      database: fret_heatmap_app_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
